# Generated by Django 5.2 on 2026-02-06 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_day', models.IntegerField(default=1)),
                ('total_duration', models.IntegerField()),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('day', models.IntegerField(default=1)),
                ('activity_description', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('photo_name', models.CharField()),
                ('address', models.CharField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.itinerary')),
                ('activity_neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_title', models.CharField(default='My Trip', help_text='Give your trip a name', max_length=255, verbose_name='Trip Title')),
                ('stay_length', models.IntegerField()),
                ('activity_window_start', models.TimeField()),
                ('activity_window_end', models.TimeField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('radius', models.IntegerField(default=1, help_text='Radius in miles from stay location')),
                ('dislikes', models.TextField(blank=True)),
                ('activity_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.activitylevel')),
                ('preferred_cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.preferredcuisine')),
                ('social_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.socialcontext')),
                ('stay_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_stay_location', to='planner.neighborhood')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.itinerary')),
            ],
            options={
                'unique_together': {('user', 'itinerary')},
            },
        ),
    ]
