# Generated by Django 5.2 on 2026-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='activity_window_end',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='activity_window_start',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='activity_duration_hours',
            field=models.IntegerField(default=4, help_text='Number of hours per day for activities', verbose_name='Activity Duration (Hours)'),
        ),
    ]
