# Generated by Django 5.2 on 2026-02-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_remove_surveyresponse_activity_window_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryactivity',
            name='address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='itineraryactivity',
            name='photo_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
